# companies.py
#
# Curated list of companies to search for jobs.
# This list acts as the combined WLB + size filter — only companies on this
# list will appear in results. Add or remove entries freely.
#
# Fields:
#   name                    - Display name
#   greenhouse_slug         - Slug used in boards.greenhouse.io/{slug} (None if not on Greenhouse)
#   lever_slug              - Slug used in jobs.lever.co/{slug} (None if not on Lever)
#   glassdoor_wlb_score     - Glassdoor work-life balance score (0-5, informational only)
#   employee_count_estimate - Rough headcount
#   notes                   - Optional freeform notes

COMPANIES = [
    # ── GREENHOUSE ────────────────────────────────────────────────────────────
    {
        "name": "Airbnb",
        "greenhouse_slug": "airbnb",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.1,
        "employee_count_estimate": 6000,
        "notes": "",
    },
    {
        "name": "Netflix",
        "greenhouse_slug": "netflix",
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 13000,
        "notes": "",
    },
    {
        "name": "Lyft",
        "greenhouse_slug": "lyft",
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 5000,
        "notes": "",
    },
    {
        "name": "DoorDash",
        "greenhouse_slug": "doordash",
        "lever_slug": None,
        "glassdoor_wlb_score": 3.6,
        "employee_count_estimate": 8000,
        "notes": "",
    },
    {
        "name": "OpenAI",
        "greenhouse_slug": "openai",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 1500,
        "notes": "",
    },
    {
        "name": "Databricks",
        "greenhouse_slug": "databricks",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.3,
        "employee_count_estimate": 5000,
        "notes": "",
    },
    {
        "name": "Coinbase",
        "greenhouse_slug": "coinbase",
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 3500,
        "notes": "",
    },
    {
        "name": "Reddit",
        "greenhouse_slug": "reddit",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 2000,
        "notes": "",
    },
    {
        "name": "Figma",
        "greenhouse_slug": "figma",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.5,
        "employee_count_estimate": 1200,
        "notes": "",
    },
    {
        "name": "Robinhood",
        "greenhouse_slug": "robinhood",
        "lever_slug": None,
        "glassdoor_wlb_score": 3.7,
        "employee_count_estimate": 2000,
        "notes": "",
    },
    {
        "name": "Dropbox",
        "greenhouse_slug": "dropbox",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 2500,
        "notes": "Remote-first company",
    },
    {
        "name": "HubSpot",
        "greenhouse_slug": "hubspot",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.5,
        "employee_count_estimate": 7000,
        "notes": "",
    },
    {
        "name": "Spotify",
        "greenhouse_slug": "spotify",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.3,
        "employee_count_estimate": 9000,
        "notes": "",
    },
    {
        "name": "Snap",
        "greenhouse_slug": "snap",
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 5000,
        "notes": "",
    },
    {
        "name": "Twilio",
        "greenhouse_slug": "twilio",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 6000,
        "notes": "",
    },
    {
        "name": "Zoom",
        "greenhouse_slug": "zoom",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.1,
        "employee_count_estimate": 7000,
        "notes": "",
    },
    {
        "name": "Asana",
        "greenhouse_slug": "asana",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.4,
        "employee_count_estimate": 1700,
        "notes": "",
    },
    {
        "name": "Waymo",
        "greenhouse_slug": "waymo",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 2500,
        "notes": "",
    },
    {
        "name": "Palantir",
        "greenhouse_slug": "palantir",
        "lever_slug": None,
        "glassdoor_wlb_score": 3.5,
        "employee_count_estimate": 4000,
        "notes": "Lower WLB score — remove if not desired",
    },
    {
        "name": "Twitch",
        "greenhouse_slug": "twitch",
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 1000,
        "notes": "Amazon subsidiary",
    },
    {
        "name": "Qualtrics",
        "greenhouse_slug": "qualtrics",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 5000,
        "notes": "",
    },
    {
        "name": "Roblox",
        "greenhouse_slug": "roblox",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.1,
        "employee_count_estimate": 2000,
        "notes": "",
    },

    # ── LEVER ─────────────────────────────────────────────────────────────────
    {
        "name": "Stripe",
        "greenhouse_slug": None,
        "lever_slug": "stripe",
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 8000,
        "notes": "",
    },
    {
        "name": "Cloudflare",
        "greenhouse_slug": None,
        "lever_slug": "cloudflare",
        "glassdoor_wlb_score": 4.1,
        "employee_count_estimate": 3500,
        "notes": "",
    },
    {
        "name": "GitLab",
        "greenhouse_slug": None,
        "lever_slug": "gitlab",
        "glassdoor_wlb_score": 4.3,
        "employee_count_estimate": 2000,
        "notes": "Fully remote company",
    },
    {
        "name": "PagerDuty",
        "greenhouse_slug": None,
        "lever_slug": "pagerduty",
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 1000,
        "notes": "",
    },
    {
        "name": "Instacart",
        "greenhouse_slug": None,
        "lever_slug": "instacart",
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 3000,
        "notes": "",
    },
    {
        "name": "Confluent",
        "greenhouse_slug": None,
        "lever_slug": "confluent",
        "glassdoor_wlb_score": 4.1,
        "employee_count_estimate": 3000,
        "notes": "",
    },
    {
        "name": "Anthropic",
        "greenhouse_slug": None,
        "lever_slug": "anthropic",
        "glassdoor_wlb_score": 4.5,
        "employee_count_estimate": 1000,
        "notes": "",
    },
    {
        "name": "Scale AI",
        "greenhouse_slug": None,
        "lever_slug": "scaleai",
        "glassdoor_wlb_score": 3.7,
        "employee_count_estimate": 1000,
        "notes": "",
    },
    {
        "name": "Duolingo",
        "greenhouse_slug": None,
        "lever_slug": "duolingo",
        "glassdoor_wlb_score": 4.4,
        "employee_count_estimate": 700,
        "notes": "Strong ML team; slightly under 1k employees",
    },
    {
        "name": "Replit",
        "greenhouse_slug": None,
        "lever_slug": "replit",
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 200,
        "notes": "Small but notable AI-first company; remove if strict about size",
    },

    # ── AGGREGATOR-ONLY (own portals — caught via Jobicy / RemoteOK) ──────────
    {
        "name": "Google",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 180000,
        "notes": "Uses own careers portal",
    },
    {
        "name": "Microsoft",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 220000,
        "notes": "Uses own careers portal",
    },
    {
        "name": "Meta",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 70000,
        "notes": "Uses own careers portal",
    },
    {
        "name": "Apple",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 160000,
        "notes": "Rarely fully remote; low yield expected",
    },
    {
        "name": "Salesforce",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.1,
        "employee_count_estimate": 70000,
        "notes": "",
    },
    {
        "name": "Adobe",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 30000,
        "notes": "",
    },
    {
        "name": "Nvidia",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.3,
        "employee_count_estimate": 30000,
        "notes": "",
    },
    {
        "name": "IBM",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 280000,
        "notes": "",
    },
    {
        "name": "LinkedIn",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 20000,
        "notes": "Microsoft subsidiary; uses own portal",
    },
    {
        "name": "Amazon",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.2,
        "employee_count_estimate": 1500000,
        "notes": "Low WLB score — remove if not desired",
    },
    {
        "name": "Intuit",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.3,
        "employee_count_estimate": 18000,
        "notes": "",
    },
    {
        "name": "ServiceNow",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 22000,
        "notes": "",
    },
    {
        "name": "Workday",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.3,
        "employee_count_estimate": 18000,
        "notes": "",
    },
    {
        "name": "Snowflake",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 7000,
        "notes": "",
    },

    # ── MORE GREENHOUSE (mid-size tech) ────────────────────────────────────────
    {
        "name": "Datadog",
        "greenhouse_slug": "datadog",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 5000,
        "notes": "",
    },
    {
        "name": "MongoDB",
        "greenhouse_slug": "mongodb",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.3,
        "employee_count_estimate": 5000,
        "notes": "",
    },
    {
        "name": "Okta",
        "greenhouse_slug": "okta",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.1,
        "employee_count_estimate": 6000,
        "notes": "",
    },
    {
        "name": "Brex",
        "greenhouse_slug": "brex",
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 1200,
        "notes": "",
    },
    {
        "name": "Nuro",
        "greenhouse_slug": "nuro",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 1000,
        "notes": "Autonomous delivery; strong ML team",
    },
    {
        "name": "Plaid",
        "greenhouse_slug": "plaid",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.3,
        "employee_count_estimate": 1000,
        "notes": "",
    },
    {
        "name": "Rippling",
        "greenhouse_slug": "rippling",
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 3000,
        "notes": "",
    },
    {
        "name": "Elastic",
        "greenhouse_slug": "elastic",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.3,
        "employee_count_estimate": 3500,
        "notes": "Remote-first company",
    },
    {
        "name": "HashiCorp",
        "greenhouse_slug": "hashicorp",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 2000,
        "notes": "Now IBM subsidiary; remote-first",
    },
    {
        "name": "Zendesk",
        "greenhouse_slug": "zendesk",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 6000,
        "notes": "",
    },
    {
        "name": "DocuSign",
        "greenhouse_slug": "docusign",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 7000,
        "notes": "",
    },
    {
        "name": "Splunk",
        "greenhouse_slug": "splunk",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 8000,
        "notes": "Now Cisco subsidiary",
    },
    {
        "name": "New Relic",
        "greenhouse_slug": "newrelic",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 2500,
        "notes": "",
    },
    {
        "name": "Dataiku",
        "greenhouse_slug": "dataiku",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.1,
        "employee_count_estimate": 1000,
        "notes": "ML platform company; strong data science hiring",
    },
    {
        "name": "Weights & Biases",
        "greenhouse_slug": "wandb",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.4,
        "employee_count_estimate": 500,
        "notes": "ML tooling; remote-friendly; under 1k but notable AI hiring",
    },
    {
        "name": "Hugging Face",
        "greenhouse_slug": None,
        "lever_slug": "huggingface",
        "glassdoor_wlb_score": 4.5,
        "employee_count_estimate": 300,
        "notes": "Fully remote; small but landmark ML company",
    },
    {
        "name": "Cohere",
        "greenhouse_slug": "cohere",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.3,
        "employee_count_estimate": 500,
        "notes": "AI/LLM company; strong research + applied scientist roles",
    },
    {
        "name": "Mistral AI",
        "greenhouse_slug": None,
        "lever_slug": "mistral",
        "glassdoor_wlb_score": 4.3,
        "employee_count_estimate": 200,
        "notes": "AI/LLM; small but high-paying for ML roles",
    },
    {
        "name": "xAI",
        "greenhouse_slug": None,
        "lever_slug": "xai",
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 1000,
        "notes": "Elon Musk AI company; high comp but unknown WLB",
    },
    {
        "name": "Perplexity AI",
        "greenhouse_slug": "perplexityai",
        "lever_slug": None,
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 300,
        "notes": "AI search; small but high-paying",
    },

    # ── MORE LEVER (mid-size tech) ─────────────────────────────────────────────
    {
        "name": "Veeva Systems",
        "greenhouse_slug": None,
        "lever_slug": "veeva",
        "glassdoor_wlb_score": 4.4,
        "employee_count_estimate": 7000,
        "notes": "Healthcare SaaS; excellent WLB reputation",
    },
    {
        "name": "Carta",
        "greenhouse_slug": None,
        "lever_slug": "carta",
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 2000,
        "notes": "",
    },
    {
        "name": "Samsara",
        "greenhouse_slug": None,
        "lever_slug": "samsara",
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 3000,
        "notes": "",
    },
    {
        "name": "Amplitude",
        "greenhouse_slug": None,
        "lever_slug": "amplitude",
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 700,
        "notes": "Product analytics; strong data science hiring",
    },

    # ── FORTUNE 500 — FINANCIAL SERVICES (aggregator-only) ────────────────────
    {
        "name": "JPMorgan Chase",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.6,
        "employee_count_estimate": 310000,
        "notes": "Fortune 500; large ML/AI team; uses own portal",
    },
    {
        "name": "Goldman Sachs",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 2.9,
        "employee_count_estimate": 45000,
        "notes": "Fortune 500; very high comp but low WLB — remove if undesired",
    },
    {
        "name": "Capital One",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 55000,
        "notes": "Fortune 500; known as a tech-forward bank with strong data culture",
    },
    {
        "name": "American Express",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 77000,
        "notes": "Fortune 500; strong data science team",
    },
    {
        "name": "Visa",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.3,
        "employee_count_estimate": 26000,
        "notes": "Fortune 500; excellent WLB; strong ML team for fraud/payments",
    },
    {
        "name": "Mastercard",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 32000,
        "notes": "Fortune 500; strong data science and AI team",
    },
    {
        "name": "PayPal",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.7,
        "employee_count_estimate": 27000,
        "notes": "Fortune 500",
    },
    {
        "name": "Fidelity Investments",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.1,
        "employee_count_estimate": 70000,
        "notes": "Fortune 500; strong quant/ML team",
    },
    {
        "name": "Charles Schwab",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 35000,
        "notes": "Fortune 500",
    },
    {
        "name": "BlackRock",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 20000,
        "notes": "Fortune 500; strong quant finance and ML hiring",
    },
    {
        "name": "Morgan Stanley",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.5,
        "employee_count_estimate": 80000,
        "notes": "Fortune 500; large tech/data team",
    },
    {
        "name": "Citigroup",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.7,
        "employee_count_estimate": 240000,
        "notes": "Fortune 500",
    },
    {
        "name": "Bank of America",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 213000,
        "notes": "Fortune 500",
    },

    # ── FORTUNE 500 — TECHNOLOGY (aggregator-only) ────────────────────────────
    {
        "name": "Oracle",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.7,
        "employee_count_estimate": 143000,
        "notes": "Fortune 500; large cloud/data platform; uses own portal",
    },
    {
        "name": "Cisco",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 85000,
        "notes": "Fortune 500",
    },
    {
        "name": "Intel",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 110000,
        "notes": "Fortune 500",
    },
    {
        "name": "Qualcomm",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 51000,
        "notes": "Fortune 500; strong ML/AI chip research",
    },
    {
        "name": "Broadcom",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.6,
        "employee_count_estimate": 60000,
        "notes": "Fortune 500",
    },
    {
        "name": "Dell Technologies",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.1,
        "employee_count_estimate": 120000,
        "notes": "Fortune 500",
    },
    {
        "name": "HP Inc",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 58000,
        "notes": "Fortune 500",
    },
    {
        "name": "Hewlett Packard Enterprise",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 62000,
        "notes": "Fortune 500",
    },
    {
        "name": "T-Mobile",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 75000,
        "notes": "Fortune 500; known for data/ML work in telecom",
    },
    {
        "name": "Verizon",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.7,
        "employee_count_estimate": 105000,
        "notes": "Fortune 500",
    },
    {
        "name": "AT&T",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.7,
        "employee_count_estimate": 160000,
        "notes": "Fortune 500",
    },
    {
        "name": "Accenture",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 750000,
        "notes": "Fortune 500; large AI/data practice",
    },

    # ── FORTUNE 500 — HEALTHCARE & PHARMA (aggregator-only) ───────────────────
    {
        "name": "UnitedHealth Group",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.7,
        "employee_count_estimate": 400000,
        "notes": "Fortune 500; Optum subsidiary has large data science team",
    },
    {
        "name": "CVS Health",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.6,
        "employee_count_estimate": 300000,
        "notes": "Fortune 500; Aetna subsidiary has analytics team",
    },
    {
        "name": "Cigna",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 73000,
        "notes": "Fortune 500",
    },
    {
        "name": "Johnson & Johnson",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.1,
        "employee_count_estimate": 150000,
        "notes": "Fortune 500; strong data science and AI team",
    },
    {
        "name": "Pfizer",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 88000,
        "notes": "Fortune 500; strong ML in drug discovery",
    },
    {
        "name": "Merck",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.2,
        "employee_count_estimate": 68000,
        "notes": "Fortune 500",
    },
    {
        "name": "Eli Lilly",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.3,
        "employee_count_estimate": 43000,
        "notes": "Fortune 500; expanding AI/ML team",
    },
    {
        "name": "AbbVie",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.1,
        "employee_count_estimate": 50000,
        "notes": "Fortune 500",
    },
    {
        "name": "Abbott Laboratories",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 115000,
        "notes": "Fortune 500",
    },
    {
        "name": "Bristol-Myers Squibb",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.1,
        "employee_count_estimate": 34000,
        "notes": "Fortune 500",
    },

    # ── FORTUNE 500 — RETAIL & CONSUMER (aggregator-only) ─────────────────────
    {
        "name": "Target",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 440000,
        "notes": "Fortune 500; strong data science team at HQ (Minneapolis)",
    },
    {
        "name": "Nike",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 79000,
        "notes": "Fortune 500; growing ML/data team",
    },
    {
        "name": "Home Depot",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.6,
        "employee_count_estimate": 465000,
        "notes": "Fortune 500; large data science team",
    },
    {
        "name": "Walmart",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.3,
        "employee_count_estimate": 2100000,
        "notes": "Fortune 500; large ML team; lower WLB — remove if undesired",
    },

    # ── FORTUNE 500 — MEDIA & ENTERTAINMENT (aggregator-only) ─────────────────
    {
        "name": "Disney",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 190000,
        "notes": "Fortune 500; growing ML/data team across streaming and parks",
    },
    {
        "name": "Comcast / NBCUniversal",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.7,
        "employee_count_estimate": 186000,
        "notes": "Fortune 500",
    },
    {
        "name": "Warner Bros Discovery",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.7,
        "employee_count_estimate": 35000,
        "notes": "Fortune 500",
    },

    # ── FORTUNE 500 — DEFENSE & AEROSPACE (aggregator-only) ───────────────────
    {
        "name": "Lockheed Martin",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 114000,
        "notes": "Fortune 500; large ML/AI team (requires US citizenship for many roles)",
    },
    {
        "name": "Boeing",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.7,
        "employee_count_estimate": 156000,
        "notes": "Fortune 500",
    },
    {
        "name": "Raytheon Technologies",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 185000,
        "notes": "Fortune 500",
    },
    {
        "name": "Northrop Grumman",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 4.0,
        "employee_count_estimate": 95000,
        "notes": "Fortune 500",
    },
    {
        "name": "General Dynamics",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 107000,
        "notes": "Fortune 500",
    },
    {
        "name": "Booz Allen Hamilton",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 33000,
        "notes": "Fortune 500; large data science / AI practice",
    },
    {
        "name": "Leidos",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 47000,
        "notes": "Fortune 500; AI/ML for government contracts",
    },
    {
        "name": "SAIC",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 26000,
        "notes": "Fortune 500; AI/ML for government contracts",
    },

    # ── FORTUNE 500 — AUTO & MOBILITY (aggregator-only) ───────────────────────
    {
        "name": "Tesla",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.2,
        "employee_count_estimate": 127000,
        "notes": "Fortune 500; high comp but notoriously poor WLB — remove if undesired",
    },
    {
        "name": "General Motors",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 163000,
        "notes": "Fortune 500; large data science team (Cruise, OnStar)",
    },
    {
        "name": "Ford",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 177000,
        "notes": "Fortune 500; growing AI/ML team",
    },

    # ── FORTUNE 500 — CONSULTING & PROFESSIONAL SERVICES (aggregator-only) ────
    {
        "name": "Deloitte",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 460000,
        "notes": "Fortune 500; large AI/data analytics practice",
    },
    {
        "name": "McKinsey & Company",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.5,
        "employee_count_estimate": 45000,
        "notes": "Fortune 500; QuantumBlack data science arm",
    },
    {
        "name": "EY",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.7,
        "employee_count_estimate": 395000,
        "notes": "Fortune 500",
    },
    {
        "name": "PwC",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 364000,
        "notes": "Fortune 500",
    },

    # ── FORTUNE 500 — INDUSTRIAL & OTHER (aggregator-only) ────────────────────
    {
        "name": "3M",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.9,
        "employee_count_estimate": 92000,
        "notes": "Fortune 500; growing data science team",
    },
    {
        "name": "Honeywell",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.8,
        "employee_count_estimate": 95000,
        "notes": "Fortune 500; AI/ML for industrial automation",
    },
    {
        "name": "General Electric",
        "greenhouse_slug": None,
        "lever_slug": None,
        "glassdoor_wlb_score": 3.7,
        "employee_count_estimate": 170000,
        "notes": "Fortune 500; GE Digital and GE Research have ML teams",
    },
]


def get_greenhouse_companies() -> list[dict]:
    """Return companies that have a Greenhouse slug."""
    return [c for c in COMPANIES if c["greenhouse_slug"]]


def get_lever_companies() -> list[dict]:
    """Return companies that have a Lever slug."""
    return [c for c in COMPANIES if c["lever_slug"]]


def get_all_company_names() -> set[str]:
    """Return a lowercase set of all company names for O(1) membership checks."""
    return {c["name"].lower() for c in COMPANIES}


def get_company_by_name(name: str) -> dict | None:
    """Case-insensitive lookup of a company entry by name."""
    name_lower = name.lower().strip()
    for c in COMPANIES:
        if c["name"].lower() == name_lower:
            return c
    return None
